version: "3.8"

services:
  # 1) MinIO: S3-compatible object store
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./minio-data:/minio-data # Mount the local folder to container
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set myminio http://localhost:9000 admin password;
      mc mb myminio/datalake;
      mc mb myminio/datalakehouse;
      mc mb myminio/warehouse;
      mc mb myminio/seed;
      mc cp /minio-data/* myminio/seed/;
      tail -f /dev/null"

  # 2) PostgreSQL: Hive Metastore metadata database
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - hive-metastore-db-data:/var/lib/postgresql/data

  # 3) Hive Metastore Thrift service
  hive-metastore:
    image: apache/hive:4.0.0
    container_name: hive-metastore
    depends_on:
      - postgres
      - minio
    ports:
      - "9083:9083"
    environment:
      SERVICE_NAME: metastore

      # These two dictate the right -dbType for SchemaTool
      DB_TYPE: postgres
      JDBC_URL: jdbc:postgresql://postgres:5432/metastore

      # These two supply the driver name & credentials
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_USER: hive
      JDBC_PASSWORD: hive

      # MinIO S3 integration
      S3_ENDPOINT_URL: http://minio:9000
      S3_BUCKET: warehouse
      S3_PREFIX: ""

  # 4) Iceberg REST Catalog service
  iceberg-rest:
    image: tabulario/iceberg-rest:0.2.0
    depends_on:
      - hive-metastore
      - minio
    ports:
      - "8181:8181"
    environment:
      ICEBERG_CATALOG_NAME: hive
      ICEBERG_HIVE_URI: thrift://hive-metastore:9083
      ICEBERG_S3_ENDPOINT: http://minio:9000
      ICEBERG_S3_ACCESS_KEY: admin
      ICEBERG_S3_SECRET_KEY: password
      ICEBERG_WAREHOUSE: s3://warehouse
      ICEBERG_S3_PATH_STYLE_ACCESS: "true"

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  hive-metastore-db-data:
    driver: local
  qdrant_data:
