version: "3.8"

services:
  # 1) MinIO: S3-compatible object store
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server /data

  # 2) PostgreSQL: Hive Metastore metadata database
  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - hive-metastore-db-data:/var/lib/postgresql/data

  # 3) Hive Metastore Thrift service
  hive-metastore:
    image: tabulario/hive-metastore:latest
    depends_on:
      - postgres
      - minio
    ports:
      - "9083:9083"
    environment:
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_DB: metastore
      HIVE_METASTORE_HOST: postgres
      HIVE_S3_ENDPOINT: http://minio:9000
      HIVE_S3_ACCESS_KEY: admin
      HIVE_S3_SECRET_KEY: password

  # 4) Iceberg REST Catalog service
  iceberg-rest:
    image: tabulario/iceberg-rest:0.2.0
    depends_on:
      - hive-metastore
      - minio
    ports:
      - "8181:8181"
    environment:
      ICEBERG_CATALOG_NAME: hive
      ICEBERG_HIVE_URI: thrift://hive-metastore:9083
      ICEBERG_S3_ENDPOINT: http://minio:9000
      ICEBERG_S3_ACCESS_KEY: admin
      ICEBERG_S3_SECRET_KEY: password
      ICEBERG_WAREHOUSE: s3://my-warehouse

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  hive-metastore-db-data:
    driver: local
  qdrant_data:
